### ISSUE TITLE
Data availiability

### ISSUE THREAD

**Issue by mizraelson** [ligalaizik/Antibody-repertoire-analysis-R-code-#1]
Hi,
I am trying to download the raw data for the paper. As I understand  every biological sample has been sequenced in two technical replicas. But I only see one pair of Fastq files (R1\R2) per sample under [PRJNA699402].

**Comment by ligalaizik** [comment]
Hi, 
The pairing of the duplicates are mentioned as S_, 
For example, for the naive lymph node you will find 8 files, 
4 files are S3, and another 4 files are S4, the S is for sample. 

You can see it here:
https://trace.ncbi.nlm.nih.gov/Traces/index.html?view=run_browser&acc=SRR13626424&display=data-access <https://trace.ncbi.nlm.nih.gov/Traces/index.html?view=run_browser&acc=SRR13626424&display=data-access>




Ligal Aizik
PhD student
Dr. Yariv Wine's research group
The Shmunis School of Biomedicine and  Cancer Research
George S. Wise Faculty of Life Sciences
Tel-Aviv University , Green Bldg. 223,
Tel-Aviv, 69978, ISRAEL
E-mail: ***@***.***

**Comment by mizraelson** [comment]
Thanks, found it.
